baseURL: 'https://xinrea.cn'
languageCode: 'zh-CN'
title: '杏仁儿'
theme: "PaperMod"
markup:
  goldmark:
    renderer:
      unsafe: true

params:
    profileMode:
        enabled: true
        subtitle: "简单生活"
        buttons:
            - name: Projects
              url: "/projects"
            - name: Posts
              url: "/posts"
            - name: Github
              url: "https://github.com/Xinrea"

    socialIcons: # optional
        - name: "bilibili"
          url: "https://space.bilibili.com/475210"
