baseURL: 'https://xinrea.cn'
languageCode: 'zh-CN'
title: '杏仁儿的博客'
theme: "PaperMod"
enableGitInfo: true
hasCJKLanguage: true
buildDrafts: true
googleAnalytics: G-YDJZ0WLTD6
markup:
  highlight:
      # anchorLineNos: true
      codeFences: true
      guessSyntax: true
      lineNos: true
      # noClasses: false
      style: monokai
  goldmark:
    renderer:
      unsafe: true

params:
    env: production
    assets:
        disableHLJS: true
    homeInfoParams:
        Title: Xinrea
        Content: TL;DR

    socialIcons: # optional
        - name: "bilibili"
          url: "https://space.bilibili.com/475210"
        - name: "GitHub"
          url: "https://github.com/Xinrea"
        - name: "email"
          url: "mailto:xinreas@outlook.com"

    ShowReadingTime: true
    ShowBreadCrumbs: true
    disqusShortname: xinrea
    defaultTheme: dark
    disableThemeToggle: true
    ShowWordCount: true
