baseURL: "https://xinrea.cn"
languageCode: "zh-CN"
title: "杏仁儿的博客"
theme: "PaperMod"
enableGitInfo: true
hasCJKLanguage: true
buildDrafts: true
googleAnalytics: G-YDJZ0WLTD6
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: false
    # noClasses: false
    style: monokai
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
menu:
  main:
    - name: Archive
      url: archives/
      weight: 1
    - name: Search
      url: search
      weight: 3
    - name: Tags
      url: tags
      weight: 2
    - name: Projects
      url: projects
      weight: 4
params:
  math: true
  env: production
  assets:
    disableHLJS: true
  homeInfoParams:
    Title: Xinrea
    Content: TL;DR

  socialIcons: # optional
    - name: "bilibili"
      url: "https://space.bilibili.com/475210"
    - name: "GitHub"
      url: "https://github.com/Xinrea"
    - name: "email"
      url: "mailto:xinreas@outlook.com"

  ShowReadingTime: true
  ShowBreadCrumbs: true
  disqusShortname: xinrea
  ShowWordCount: true
  defaultTheme: auto
  editPost:
    URL: "https://github.com/Xinrea/Xinrea.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
